Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:provider.stage}-user-pool
      AutoVerifiedAttributes:
        - email

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool