service: api
app: transportation-iot
org: opentransportmonitoring

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: API-${self:provider.stage}
    authenticationType: API_KEY
    dataSources:
      - type: AWS_LAMBDA
        name: allDevices
        description: 'Get all devices'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: device-${self:provider.stage}-getRegisteredDevices
      - type: AWS_LAMBDA
        name: createDevice
        description: 'Create device'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: device-${self:provider.stage}-registerIotDevice
      - type: AWS_LAMBDA
        name: addVehicle
        description: 'Add vehicle'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-addVehicle
      - type: AWS_LAMBDA
        name: deleteVehicle
        description: 'Delete vehicle'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-deleteVehicle
      - type: AWS_LAMBDA
        name: getAllVehicles
        description: 'Get all vehicles'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-getAllVehicles
      - type: AWS_LAMBDA
        name: getVehicle
        description: 'Get vehicle'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-getVehicle
      - type: AWS_LAMBDA
        name: updateVehicle
        description: 'Update vehicle'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-updateVehicle
      - type: AWS_LAMBDA
        name: getVehicleParameterLimits
        description: 'Get vehicle parameter limits'
        config:
          lambdaFunctionArn:
            Fn::ImportValue: vehicle-${self:provider.stage}-getVehicleParameterLimits
    mappingTemplates:
      - dataSource: allDevices
        type: Query
        field: allDevices
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: createDevice
        type: Mutation
        field: createDevice
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: addVehicle
        type: Mutation
        field: addVehicle
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: getVehicle
        type: Query
        field: singleVehicle
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: getVehicleParameterLimits
        type: Query
        field: vehicleParameterLimits
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: getAllVehicles
        type: Query
        field: allVehicles
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: updateVehicle
        type: Mutation
        field: updateVehicle
        request: standard.request.vtl
        response: standard.response.vtl
      - dataSource: deleteVehicle
        type: Mutation
        field: deleteVehicle
        request: standard.request.vtl
        response: standard.response.vtl
