Resources:
  deviceRegisteredTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: iot_device_registered_${self:provider.stage}

  deviceCertificatesCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: iot_device_certificates_created_${self:provider.stage}