service: events
app: transportation-iot
org: opentransportmonitoring

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

resources:
  - ${file(resources/device_messages_database.yml)}
  - ${file(resources/device_messages_database_access_role.yml)}
  - ${file(resources/device_messages_persistence_iot_rule.yml)}
