service: device-layer
app: transportation-iot
org: opentransportmonitoring

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

plugins:
  - serverless-scriptable-plugin

custom:
  runtime: python3.7
  artifact: .serverless/device.zip
  scriptHooks:
    after:package:createDeploymentArtifacts: python ../../scripts/prepare_custom_layer.py . ${self:custom.artifact} ${self:custom.runtime}

layers:
  device:
    package:
      artifact: ${self:custom.artifact}
    compatibleRuntimes:
      - ${self:custom.runtime}

resources:
  Outputs:
    deviceLayerExport:
        Value:
          Ref: DeviceLambdaLayer
        Export:
          Name: DeviceLambdaLayer-${self:provider.stage}