service: device
app: transportation-iot
org: opentransportmonitoring

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

plugins:
  - serverless-iam-roles-per-function
  - serverless-s3-sync

package:
  individually: true
  exclude:
    - "**/*"

custom:
  s3Sync:
    - bucketNameKey: CertificatesStorageBucketName
      localDir: assets

functions:
  - ${file(create_device_certificates/description.yml)}
  - ${file(register_iot_device/description.yml)}
  - ${file(store_device_certificates/description.yml)}
  - ${file(get_device_certificates/description.yml)}
  - ${file(get_registered_devices/description.yml)}

resources:
  - ${file(resources/iot_device_policy.yml)}
  - ${file(resources/iot_certificates_storage.yml)}
  - ${file(resources/device_operation_topics.yml)}
  - ${file(stack_outputs.yml)}